name: NodeJS CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup PostgreSQL
        uses: Harmon758/postgresql-action@v1.0.0
        with:
          postgresql version: '12'
          postgresql user: pg_user
          postgresql password: pg_pass

      - name: Wait / Sleep
        uses: jakejarvis/wait-action@v0.1.0
        with:
          time: '10s'

      - name: Collect Docker Logs
        uses: jwalton/gh-docker-logs@v1.0.0

      - name: Check running containers
        run: docker ps -a

      - name: Install NPM dependencies
        run: npm install

      - name: Run Tests
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DB_USER: pg_user
          DB_PASSWORD: pg_pass
          MAIL_HOST: ${{ secrets.MAIL_HOST }}
          MAIL_PORT: ${{ secrets.MAIL_PORT }}
          MAIL_USER: ${{ secrets.MAIL_USER }}
          MAIL_PASS: ${{ secrets.MAIL_PASS }}
        run: |
          bash scripts/environment.sh
          npm run pretest
          npm run test:coverage
          npm run posttest

      - name: Codecov
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

        env:
          CI: true
